[build]
  publish = "public"
  functions = "netlify/functions"

[functions.ayuda]
  timeout = 26

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
